In [1]:
import pandas as pd

In [2]:
log1 = pd.read_csv('log1.txt')
log1.head()

            name           phone                   email         country
0  Damon Gregory  1-586-365-8458         orci@google.net  United Kingdom
1   Richard Kirk  (946) 317-6611        purus@icloud.net       Singapore
2    Dieter Howe  1-628-723-8328  gravida@protonmail.net          Norway
3     Alec Walls  (864) 881-4414   et.rutrum@hotmail.com          Norway
4   Damian White  1-708-404-5549  in.scelerisque@aol.org            Peru

In [3]:
log2= pd.read_csv('log2.txt')
log2.head()

,name,phone,email,country
0,Ezekiel Stein,1-263-951-9851,blandit@icloud.edu,Belgium
1,Cailin Luna,1-846-476-6395,odio.vel.est@hotmail.com,South Africa
2,Brenden Mueller,1-874-489-1722,cursus.nunc.mauris@hotmail.ca,India
3,Germaine Santiago,1-984-997-6672,et.euismod@outlook.couk,Ukraine
4,Caesar Larsen,1-746-457-2253,facilisis.eget.ipsum@hotmail.edu,Singapore

In [4]:
log3= pd.read_csv('log3.txt')
log3.head()

            name           phone                     email       country
0     Magee Ruiz  1-396-268-5342  bibendum.sed.est@aol.org     Singapore
1   Zena Mcclain  (938) 978-1236             in@yahoo.couk   Philippines
2  Naomi Mccarty  (608) 874-9269    risus.nulla@google.net  South Africa
3      Hop Moses  1-334-777-5292      diam.duis@google.org       Ukraine
4  Brandon Klein  (836) 600-8172     sit.amet@hotmail.couk        Turkey

In [5]:
df = pd.concat((log1, log2, log3))

In [7]:
df.head(15)

,name,phone,email,country
0,Damon Gregory,1-586-365-8458,orci@google.net,United Kingdom
1,Richard Kirk,(946) 317-6611,purus@icloud.net,Singapore
2,Dieter Howe,1-628-723-8328,gravida@protonmail.net,Norway
3,Alec Walls,(864) 881-4414,et.rutrum@hotmail.com,Norway
4,Damian White,1-708-404-5549,in.scelerisque@aol.org,Peru
0,Ezekiel Stein,1-263-951-9851,blandit@icloud.edu,Belgium
1,Cailin Luna,1-846-476-6395,odio.vel.est@hotmail.com,South Africa
2,Brenden Mueller,1-874-489-1722,cursus.nunc.mauris@hotmail.ca,India
3,Germaine Santiago,1-984-997-6672,et.euismod@outlook.couk,Ukraine
4,Caesar Larsen,1-746-457-2253,facilisis.eget.ipsum@hotmail.edu,Singapore
0,Magee Ruiz,1-396-268-5342,bibendum.sed.est@aol.org,Singapore
1,Zena Mcclain,(938) 978-1236,in@yahoo.couk,Philippines
2,Naomi Mccarty,(608) 874-9269,risus.nulla@google.net,South Africa
3,Hop Moses,1-334-777-5292,diam.duis@google.org,Ukraine
4,Brandon Klein,(836) 600-8172,sit.amet@hotmail.couk,Turkey

In [8]:
df = pd.concat((log1, log2, log3), ignore_index=True) # to reset index
df.head(15)

,name,phone,email,country
0,Damon Gregory,1-586-365-8458,orci@google.net,United Kingdom
1,Richard Kirk,(946) 317-6611,purus@icloud.net,Singapore
2,Dieter Howe,1-628-723-8328,gravida@protonmail.net,Norway
3,Alec Walls,(864) 881-4414,et.rutrum@hotmail.com,Norway
4,Damian White,1-708-404-5549,in.scelerisque@aol.org,Peru
5,Ezekiel Stein,1-263-951-9851,blandit@icloud.edu,Belgium
6,Cailin Luna,1-846-476-6395,odio.vel.est@hotmail.com,South Africa
7,Brenden Mueller,1-874-489-1722,cursus.nunc.mauris@hotmail.ca,India
8,Germaine Santiago,1-984-997-6672,et.euismod@outlook.couk,Ukraine
9,Caesar Larsen,1-746-457-2253,facilisis.eget.ipsum@hotmail.edu,Singapore
10,Magee Ruiz,1-396-268-5342,bibendum.sed.est@aol.org,Singapore
11,Zena Mcclain,(938) 978-1236,in@yahoo.couk,Philippines
12,Naomi Mccarty,(608) 874-9269,risus.nulla@google.net,South Africa
13,Hop Moses,1-334-777-5292,diam.duis@google.org,Ukraine
14,Brandon Klein,(836) 600-8172,sit.amet@hotmail.couk,Turkey

In [9]:
# what if you have 1000 of files

from glob import glob #use glob libraries

In [12]:
files = glob('log*')

In [13]:
files

['log1.txt', 'log2.txt', 'log3.txt', 'log4.txt', 'log5.txt']

In [15]:
files.sort() # for sorting
files

['log1.txt', 'log2.txt', 'log3.txt', 'log4.txt', 'log5.txt']

In [17]:
df = pd.concat((pd.read_csv(file) for file in files), ignore_index=True)

In [18]:
df.head()

            name           phone                   email         country
0  Damon Gregory  1-586-365-8458         orci@google.net  United Kingdom
1   Richard Kirk  (946) 317-6611        purus@icloud.net       Singapore
2    Dieter Howe  1-628-723-8328  gravida@protonmail.net          Norway
3     Alec Walls  (864) 881-4414   et.rutrum@hotmail.com          Norway
4   Damian White  1-708-404-5549  in.scelerisque@aol.org            Peru

In [20]:
df.head(30)

,name,phone,email,country
0,Damon Gregory,1-586-365-8458,orci@google.net,United Kingdom
1,Richard Kirk,(946) 317-6611,purus@icloud.net,Singapore
2,Dieter Howe,1-628-723-8328,gravida@protonmail.net,Norway
3,Alec Walls,(864) 881-4414,et.rutrum@hotmail.com,Norway
4,Damian White,1-708-404-5549,in.scelerisque@aol.org,Peru
5,Ezekiel Stein,1-263-951-9851,blandit@icloud.edu,Belgium
6,Cailin Luna,1-846-476-6395,odio.vel.est@hotmail.com,South Africa
7,Brenden Mueller,1-874-489-1722,cursus.nunc.mauris@hotmail.ca,India
8,Germaine Santiago,1-984-997-6672,et.euismod@outlook.couk,Ukraine
9,Caesar Larsen,1-746-457-2253,facilisis.eget.ipsum@hotmail.edu,Singapore
10,Magee Ruiz,1-396-268-5342,bibendum.sed.est@aol.org,Singapore
11,Zena Mcclain,(938) 978-1236,in@yahoo.couk,Philippines
12,Naomi Mccarty,(608) 874-9269,risus.nulla@google.net,South Africa
13,Hop Moses,1-334-777-5292,diam.duis@google.org,Ukraine
14,Brandon Klein,(836) 600-8172,sit.amet@hotmail.couk,Turkey
15,Jared Kidd,1-206-924-6934,suspendisse.sed@outlook.org,New Zealand
16,Marny Carpenter,1-877-824-8918,placerat@protonmail.com,Germany
17,Nolan Martinez,1-507-476-3526,ipsum@aol.net,Peru
18,Linus Melton,1-361-582-9372,ullamcorper.eu@icloud.edu,China
19,Ignacia Andrews,1-484-876-3752,nec.mauris@icloud.org,Costa Rica
20,Elton Paul,(455) 741-9623,pulvinar.arcu@aol.couk,Costa Rica
21,Portia Whitfield,(847) 714-0719,donec@outlook.edu,South Africa
22,Leah Harrell,1-618-189-4734,adipiscing.elit.etiam@protonmail.org,Ireland
23,Price Herrera,(385) 327-2621,bibendum@google.couk,Pakistan
24,Jordan Steele,1-237-223-7839,sociis@google.com,Netherlands
25,Yoko Howe,1-546-524-4524,consequat.dolor@google.com,Russian Federation
26,Kelsey Valenzuela,1-869-777-4743,dolor.nonummy@hotmail.org,New Zealand
27,Destiny Anderson,1-197-257-9559,erat.in@icloud.net,Russian Federation
28,Signe Compton,(266) 707-2223,facilisis.non@icloud.ca,Austria
29,Natalie Tucker,1-588-831-8654,duis@aol.com,India